on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: |
        pip install -r requirements.txt
        alias top_dir="/home/runner/work/chaldene/chaldene"
        alias start_dir="$(top_dir)/tests"
        echo $(top_dir)
        echo $(start_dir)
        echo "------------"
        python -m unittest discover -s $(start_dir) -t $(top_dir)
